server:
    port: ${PORT:8080}
    shutdown: graceful

spring:
    config:
        activate:
            on-profile: local
    lifecycle:
        timeout-per-shutdown-phase: 1m
    main:
        allow-circular-references: true
    servlet:
        multipart:
            maxFileSize: 10MB
            maxRequestSize: 10MB
    thymeleaf:
        prefix: classpath:templates/
        check-template-location: true
        suffix: .html
        mode: HTML5
        cache: false  # 프론트 자동 시작 개발 false, 운영 true
        order: 0
    devtools:
        livereload:
            enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shopadmin?serverTimezone=UTC&characterEncoding=UTF-8
        username: shop
        password: shop

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        database: mysql
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        open-in-view: false

springdoc:
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        path: /swagger-ui.html
        displayRequestDuration: true
        groups-order: DESC

logging: # ROOT 로깅
    level:
        root: info
        com.comas.work: debug
        org.hibernate:
            SQL: debug
#      type.descriptor.sql.BasicBinder: trace

decorator:
    datasource:
        p6spy:
            enable-logging: true
