server:
    port: ${PORT:8080}
    shutdown: graceful
spring:
    config:
        activate:
            on-profile: local
    lifecycle:
        timeout-per-shutdown-phase: 1m
    main:
        allow-circular-references: true
    servlet:
        multipart:
            maxFileSize: 10MB
            maxRequestSize: 10MB
    thymeleaf:
        prefix: classpath:templates/
        check-template-location: true
        suffix: .html
        mode: HTML5
        cache: false  # 프론트 자동 시작 개발 false, 운영 true
        order: 0
    devtools:
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        database: mysql
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        open-in-view: false

database:
    entity: com.shop.shopadmin.entity
    datasource:
        username: shop
        password: shop
        driver-class-name: com.mysql.cj.jdbc.Driver
        connection-timeout: 10000 # default 30000
        maximum-pool-size: 5 # default 10
        minimum-idle: 1 # default maximumPoolSize
        connection-test-query: select 1
        validation-timeout: 5000  # default 5000
        idle-timeout: 600000 # default 600000
        jdbc-url: jdbc:mysql://localhost:3306/shopadmin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    mybatis:
        config-location: classpath:/mybatis-config.xml
        mapper-locations: classpath:/sql/*-sql.xml


springdoc:
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        path: /swagger-ui.html
        displayRequestDuration: true
        groups-order: DESC

logging: # ROOT 로깅
    level:
        root: info
        com.comas.work: debug
        org.hibernate:
            SQL: debug
#      type.descriptor.sql.BasicBinder: trace

decorator:
    datasource:
        p6spy:
            enable-logging: true
